/**
 * Third-party PWA catalog
 * App Shop reads this list and registers each app through PWALoader.
 */

window.FluentPWACatalog = [
    {
        id: 'camera',
        name: '相机',
        category: 'tools',
        icon: 'camera.png',
        developer: 'Fluent OS',
        rating: 4.7,
        downloads: '预装',
        featured: true,
        appType: 'native',
        isNative: true,
        defaultInstalled: true,
        component: 'CameraApp',
        titleKey: 'camera.title',
        width: 1100,
        height: 720,
        minWidth: 760,
        minHeight: 520,
        themeColor: '#2563eb',
        desc: 'Fluent OS 原生相机应用，支持摄像头预览、拍照和下载照片。'
    },
    {
        id: 'photos',
        name: '照片',
        category: 'lifestyle',
        icon: 'photos.png',
        developer: 'Fluent OS',
        rating: 4.8,
        downloads: '预装',
        featured: true,
        appType: 'native',
        isNative: true,
        defaultInstalled: true,
        component: 'PhotosApp',
        titleKey: 'photos.title',
        width: 1000,
        height: 700,
        themeColor: '#0f6cbd',
        desc: 'Fluent OS 原生照片应用，可浏览和编辑图片，并使用 Bing 每日精选壁纸。'
    },
    {
        id: 'media',
        name: '多媒体',
        category: 'music',
        icon: 'media.png',
        developer: 'Fluent OS',
        rating: 4.8,
        downloads: '预装',
        featured: true,
        appType: 'native',
        isNative: true,
        defaultInstalled: true,
        component: 'MediaApp',
        titleKey: 'media.title',
        width: 980,
        height: 640,
        minWidth: 640,
        minHeight: 360,
        themeColor: '#0078d4',
        desc: 'Fluent OS 原生多媒体应用，可播放本地音乐和视频，支持文件与文件夹导入。'
    },
    {
        id: 'office',
        name: 'Office',
        category: 'office',
        icon: 'office.png',
        developer: 'Ziziyi Office',
        rating: 4.8,
        downloads: '10万+',
        featured: true,
        banner: true,
        url: 'https://office.ziziyi.com/',
        themeColor: '#2563eb',
        desc: '在线 Office 办公入口，支持文档、表格、演示等常用办公场景。'
    },
    {
        id: 'shimo-office',
        name: '石墨文档',
        category: 'office',
        icon: 'shimo_office.png',
        developer: 'Shimo',
        rating: 4.7,
        downloads: '500万+',
        featured: true,
        url: 'https://shimo.im/',
        themeColor: '#2f80ed',
        desc: '多人协作文档、表格和知识管理工具。'
    },
    {
        id: 'qq-mail',
        name: 'QQ邮箱',
        category: 'office',
        icon: 'email.png',
        developer: 'Tencent',
        rating: 4.5,
        downloads: '3亿+',
        url: 'https://mail.qq.com/',
        themeColor: '#1e90ff',
        desc: '腾讯邮箱服务，适合邮件、日程和附件管理。'
    },
    {
        id: 'didaqingdan',
        name: '滴答清单',
        category: 'office',
        icon: 'didaqingdan.png',
        developer: 'Dida',
        rating: 4.6,
        downloads: '1000万+',
        url: 'https://www.dida365.com/',
        themeColor: '#4772fa',
        desc: '任务、日程和清单管理工具。'
    },
    {
        id: 'canva',
        name: 'Canva',
        category: 'office',
        icon: 'canva.png',
        developer: 'Canva',
        rating: 4.8,
        downloads: '1亿+',
        featured: true,
        openMode: 'external',
        url: 'https://www.canva.com/',
        themeColor: '#00c4cc',
        desc: '在线设计平台，可制作海报、演示文稿、社交媒体图片等内容。'
    },
    {
        id: 'chatgpt',
        name: 'ChatGPT',
        category: 'ai',
        icon: 'chatgpt.png',
        developer: 'OpenAI',
        rating: 4.9,
        downloads: '1亿+',
        featured: true,
        openMode: 'external',
        url: 'https://chatgpt.com/',
        themeColor: '#10a37f',
        desc: 'OpenAI 的 AI 助手，可用于写作、编程、学习和创意探索。'
    },
    {
        id: 'deepseek',
        name: 'DeepSeek',
        category: 'ai',
        icon: 'deepseek.png',
        developer: 'DeepSeek',
        rating: 4.8,
        downloads: '5000万+',
        openMode: 'external',
        url: 'https://chat.deepseek.com/',
        themeColor: '#4d6bff',
        desc: 'DeepSeek 在线 AI 对话与推理助手。'
    },
    {
        id: 'qwen',
        name: 'Qwen',
        category: 'ai',
        icon: 'qwen.png',
        developer: 'Alibaba Cloud',
        rating: 4.7,
        downloads: '1000万+',
        openMode: 'external',
        url: 'https://chat.qwen.ai/',
        themeColor: '#615ced',
        desc: '通义千问 Qwen 的在线 AI 对话入口。'
    },
    {
        id: 'kimi',
        name: 'Kimi AI',
        category: 'ai',
        icon: 'kimi.png',
        developer: 'Moonshot AI',
        rating: 4.8,
        downloads: '1000万+',
        featured: true,
        url: 'https://www.kimi.com/',
        themeColor: '#111827',
        desc: 'Kimi AI 在线智能助手，适合长文本阅读、写作、搜索和问答。'
    },
    {
        id: 'baidu',
        name: '百度',
        category: 'tools',
        icon: 'baidu.png',
        developer: 'Baidu',
        rating: 4.5,
        downloads: '10亿+',
        url: 'https://www.baidu.com/',
        themeColor: '#2932e1',
        desc: '百度搜索和信息服务入口。'
    },
    {
        id: 'baidu-netdisk',
        name: '百度网盘',
        category: 'tools',
        icon: 'baidudisk.png',
        developer: 'Baidu',
        rating: 4.2,
        downloads: '3亿+',
        url: 'https://pan.baidu.com/',
        themeColor: '#06a7ff',
        desc: '百度云存储服务，支持文件保存、同步和分享。'
    },
    {
        id: 'youdaofanyi',
        name: '有道翻译',
        category: 'tools',
        icon: 'youdaofanyi.png',
        developer: 'NetEase',
        rating: 4.6,
        downloads: '1亿+',
        url: 'https://fanyi.youdao.com/',
        themeColor: '#e84b3c',
        desc: '网易有道在线翻译、词典和语言学习工具。'
    },
    {
        id: 'coolapk',
        name: '酷安',
        category: 'tools',
        icon: 'app_gallery.png',
        developer: 'Coolapk',
        rating: 4.5,
        downloads: '5000万+',
        openMode: 'external',
        url: 'https://www.coolapk.com/',
        themeColor: '#11b566',
        desc: '应用、数码和科技消费社区。'
    },
    {
        id: 'bilibili',
        name: '哔哩哔哩',
        category: 'video',
        icon: 'bilibili.png',
        developer: 'Bilibili',
        rating: 4.6,
        downloads: '3亿+',
        featured: true,
        url: 'https://www.bilibili.com/',
        themeColor: '#fb7299',
        desc: '年轻人喜爱的综合视频社区，包含动画、游戏、科技、生活等内容。'
    },
    {
        id: 'youku',
        name: '优酷',
        category: 'video',
        icon: 'youku.png',
        developer: 'Youku',
        rating: 4.4,
        downloads: '3亿+',
        openMode: 'external',
        url: 'https://www.youku.com/',
        themeColor: '#00a0e9',
        desc: '在线视频平台，提供影视、综艺、动漫等内容。'
    },
    {
        id: 'douyin',
        name: '抖音',
        category: 'video',
        icon: 'douyin.png',
        developer: 'ByteDance',
        rating: 4.7,
        downloads: '10亿+',
        openMode: 'external',
        url: 'https://www.douyin.com/',
        themeColor: '#111111',
        desc: '短视频和直播内容平台。'
    },
    {
        id: 'douyu',
        name: '斗鱼直播',
        category: 'video',
        icon: 'douyuzhibo.png',
        developer: 'Douyu',
        rating: 4.3,
        downloads: '1亿+',
        url: 'https://www.douyu.com/',
        themeColor: '#ff5d23',
        desc: '游戏、娱乐、户外等直播内容平台。'
    },
    {
        id: 'qq-music',
        name: 'QQ音乐',
        category: 'music',
        icon: 'qqmusic.png',
        developer: 'Tencent Music',
        rating: 4.6,
        downloads: '8亿+',
        featured: true,
        url: 'https://y.qq.com/',
        themeColor: '#31c27c',
        desc: '腾讯音乐平台，提供正版音乐、歌单、电台和音乐社区服务。'
    },
    {
        id: 'kugou-music',
        name: '酷狗音乐',
        category: 'music',
        icon: 'km1.png',
        developer: 'Kugou',
        rating: 4.5,
        downloads: '5亿+',
        openMode: 'external',
        url: 'https://www.kugou.com/',
        themeColor: '#00a9ff',
        desc: '在线音乐平台，提供歌曲、歌单、MV 和音乐内容。'
    },
    {
        id: 'netease-music',
        name: '网易云音乐',
        category: 'music',
        icon: 'wangyiyun_music.png',
        developer: 'NetEase',
        rating: 4.7,
        downloads: '5亿+',
        url: 'https://music.163.com/',
        themeColor: '#e60026',
        desc: '网易云音乐网页入口，适合发现音乐、歌单和评论社区。'
    },
    {
        id: 'weibo',
        name: '微博',
        category: 'social',
        icon: 'WB.png',
        developer: 'Sina',
        rating: 4.4,
        downloads: '5亿+',
        url: 'https://weibo.com/',
        themeColor: '#e6162d',
        desc: '中文社交媒体平台，支持图文、视频和热点讨论。'
    },
    {
        id: 'taobao',
        name: '淘宝',
        category: 'shopping',
        icon: 'taobao.png',
        developer: 'Alibaba',
        rating: 4.5,
        downloads: '10亿+',
        url: 'https://www.taobao.com/',
        themeColor: '#ff5000',
        desc: '综合网络购物平台。'
    },
    {
        id: 'jd',
        name: '京东',
        category: 'shopping',
        icon: 'jingdong.png',
        developer: 'JD.com',
        rating: 4.6,
        downloads: '5亿+',
        url: 'https://www.jd.com/',
        themeColor: '#e2231a',
        desc: '综合网购平台，提供自营和第三方商家商品。'
    },
    {
        id: 'xianyu',
        name: '闲鱼',
        category: 'shopping',
        icon: 'xianyu.png',
        developer: 'Alibaba',
        rating: 4.4,
        downloads: '3亿+',
        url: 'https://www.goofish.com/',
        themeColor: '#ffe500',
        desc: '闲置交易与二手商品平台。'
    },
    {
        id: 'taobao-shangou',
        name: '淘宝闪购',
        category: 'shopping',
        icon: 'taobaoshangou.png',
        developer: 'Alibaba',
        rating: 4.3,
        downloads: '1亿+',
        openMode: 'external',
        url: 'https://www.taobao.com/',
        themeColor: '#ff7a00',
        desc: '淘宝即时零售入口，使用淘宝官方网页作为入口。'
    },
    {
        id: 'alipay',
        name: '支付宝',
        category: 'lifestyle',
        icon: 'zhifubao.png',
        developer: 'Ant Group',
        rating: 4.7,
        downloads: '10亿+',
        url: 'https://www.alipay.com/',
        themeColor: '#1677ff',
        desc: '支付宝官方服务入口。'
    },
    {
        id: 'meituan',
        name: '美团',
        category: 'lifestyle',
        icon: 'meituan.png',
        developer: 'Meituan',
        rating: 4.5,
        downloads: '5亿+',
        url: 'https://www.meituan.com/',
        themeColor: '#ffc300',
        desc: '本地生活服务平台，包含外卖、酒店、电影票等服务。'
    },
    {
        id: 'ele-me',
        name: '饿了么',
        category: 'lifestyle',
        icon: 'meituan.png',
        developer: 'Alibaba',
        rating: 4.4,
        downloads: '3亿+',
        openMode: 'external',
        url: 'https://www.ele.me/',
        themeColor: '#0097ff',
        desc: '本地生活和即时配送服务平台。'
    },
    {
        id: 'didi',
        name: '滴滴出行',
        category: 'travel',
        icon: 'didi.png',
        developer: 'DiDi',
        rating: 4.5,
        downloads: '5亿+',
        url: 'https://www.didi.cn/',
        themeColor: '#ff7a00',
        desc: '滴滴出行官方入口。'
    },
    {
        id: 'amap',
        name: '高德地图',
        category: 'travel',
        icon: 'gaode.png',
        developer: 'Alibaba',
        rating: 4.6,
        downloads: '8亿+',
        url: 'https://www.amap.com/',
        themeColor: '#0091ff',
        desc: '高德地图网页版，提供地图、路线和位置服务。'
    },
    {
        id: 'baidu-map',
        name: '百度地图',
        category: 'travel',
        icon: 'baidu_map.png',
        developer: 'Baidu',
        rating: 4.5,
        downloads: '5亿+',
        url: 'https://map.baidu.com/',
        themeColor: '#2d67ff',
        desc: '百度地图网页版，提供地点搜索、路线规划和地图服务。'
    },
    {
        id: 'chinadaily',
        name: 'China Daily',
        category: 'news',
        icon: 'chinadaily.png',
        developer: 'China Daily',
        rating: 4.4,
        downloads: '1000万+',
        url: 'https://www.chinadaily.com.cn/',
        themeColor: '#d71920',
        desc: 'China Daily 官方新闻入口。'
    },
    {
        id: 'itzhijia',
        name: 'IT之家',
        category: 'news',
        icon: 'itzhijia.png',
        developer: 'IT之家',
        rating: 4.6,
        downloads: '5000万+',
        url: 'https://www.ithome.com/',
        themeColor: '#d80000',
        desc: '科技新闻、数码资讯和软件信息平台。'
    },
    {
        id: 'pengpai',
        name: '澎湃新闻',
        category: 'news',
        icon: 'pengpai.png',
        developer: 'The Paper',
        rating: 4.4,
        downloads: '3000万+',
        url: 'https://www.thepaper.cn/',
        themeColor: '#e43d30',
        desc: '澎湃新闻官方网页入口。'
    },
    {
        id: 'whiteboard',
        name: '白板',
        category: 'office',
        icon: 'whiteboard.png',
        developer: 'WBO',
        rating: 4.6,
        downloads: '100万+',
        url: 'https://wbo.ophir.dev/?lang=zh-CN',
        themeColor: '#f3f4f6',
        desc: '在线协作白板，适合草图、讨论和临时创作。'
    },
    {
        id: 'audiobook',
        name: '听书',
        category: 'lifestyle',
        icon: 'tinshu.png',
        developer: '爱听书',
        rating: 4.4,
        downloads: '100万+',
        url: 'https://www.itingshu.net/',
        themeColor: '#f59e0b',
        desc: '在线有声书和听书内容入口。'
    },
    {
        id: 'solitaire',
        name: '极简扑克',
        category: 'games',
        icon: 'puke.png',
        developer: 'Solitaire Online',
        rating: 4.5,
        downloads: '100万+',
        url: 'https://solitaire.online/zh',
        themeColor: '#236b4f',
        desc: '在线纸牌游戏，打开即可游玩。'
    },
    {
        id: 'jiazhaoba',
        name: '驾照吧',
        category: 'tools',
        icon: 'jiazhaoba.png',
        developer: '驾照吧',
        rating: 4.5,
        downloads: '100万+',
        url: 'https://www.jiazhaoba.com/kaoshi/',
        themeColor: '#2563eb',
        desc: '驾考题库和模拟考试练习入口。'
    },
    {
        id: 'traffic-12123',
        name: '交管12123',
        category: 'tools',
        icon: '12123.png',
        developer: '公安部交通管理局',
        rating: 4.6,
        downloads: '1亿+',
        featured: true,
        url: 'https://gab.122.gov.cn/m/login',
        themeColor: '#1e63b6',
        desc: '公安部交通安全综合服务管理平台移动入口，支持交管业务在线办理。'
    },
    {
        id: 'zujuan',
        name: '组卷网',
        category: 'office',
        icon: 'zujuanwang.png',
        developer: '学科网',
        rating: 4.6,
        downloads: '500万+',
        url: 'https://zujuan.xkw.com/',
        themeColor: '#1677ff',
        desc: '在线题库和智能组卷平台，适合教师备课、组卷和教学资源管理。'
    },
    {
        id: 'metool',
        name: 'MeTool',
        category: 'tools',
        icon: 'metool.png',
        developer: 'MeTool',
        rating: 4.7,
        downloads: '100万+',
        url: 'https://metool.online/zh',
        themeColor: '#3b82f6',
        desc: '在线工具集合，提供格式转换、编码解码、文本处理等常用工具。'
    },
    {
        id: 'video-editor',
        name: '视频编辑器',
        category: 'video',
        icon: 'videoeditor.png',
        developer: '123apps',
        rating: 4.6,
        downloads: '100万+',
        url: 'https://videocutter.io/zh/',
        themeColor: '#7c3aed',
        desc: '在线视频剪辑工具，可进行裁剪、压缩、转换和基础视频编辑。'
    },
    {
        id: 'techie-delight',
        name: 'Techie Delight',
        category: 'tools',
        icon: 'Techie Delight.png',
        developer: 'Techie Delight',
        rating: 4.6,
        downloads: '50万+',
        url: 'https://www.techiedelight.com/compiler/zh/index',
        themeColor: '#0f172a',
        desc: '在线编译器与编程学习工具，支持多语言代码运行和算法练习。'
    },
    {
        id: 'geekfa',
        name: '极客坊',
        category: 'tools',
        icon: 'jikefang.png',
        developer: 'GeekFa',
        rating: 4.5,
        downloads: '50万+',
        url: 'https://tool.geekfa.com/',
        themeColor: '#111827',
        desc: '在线工具集合，适合日常格式转换和小工具使用。'
    },
    {
        id: 'snake-classic',
        name: '经典贪吃蛇',
        category: 'games',
        icon: 'snake.png',
        developer: 'Snake',
        rating: 4.6,
        downloads: '100万+',
        url: 'https://snake.org.cn/',
        themeColor: '#16a34a',
        desc: '经典贪吃蛇网页游戏。'
    },
    {
        id: 'photopea',
        name: 'Photopea',
        category: 'office',
        icon: 'photopea.png',
        developer: 'Photopea',
        rating: 4.8,
        downloads: '1000万+',
        featured: true,
        url: 'https://www.photopea.com/#',
        themeColor: '#1f2937',
        desc: '在线图片编辑器，支持 PSD、图片处理和设计编辑。'
    },
    {
        id: 'yangshipin',
        name: '央视频',
        category: 'video',
        icon: 'yangshi.png',
        developer: 'CMG',
        rating: 4.4,
        downloads: '1亿+',
        openMode: 'external',
        url: 'https://www.yangshipin.cn/',
        themeColor: '#c90000',
        desc: '中央广播电视总台旗下视频平台。'
    },
    {
        id: 'pdf-tools',
        name: 'PDF工具',
        category: 'tools',
        icon: 'pdf.png',
        developer: 'iLovePDF',
        rating: 4.6,
        downloads: '1亿+',
        url: 'https://www.ilovepdf.com/',
        themeColor: '#e5322d',
        desc: '在线 PDF 合并、压缩、转换和编辑工具。'
    },
    {
        id: 'todo',
        name: 'Microsoft To Do',
        category: 'office',
        icon: 'todo.png',
        developer: 'Microsoft',
        rating: 4.5,
        downloads: '5000万+',
        url: 'https://to-do.office.com/tasks/',
        themeColor: '#2564cf',
        desc: '微软待办事项和任务管理入口。'
    },
    {
        id: 'translator',
        name: 'Microsoft 翻译',
        category: 'tools',
        icon: 'translator.png',
        developer: 'Microsoft',
        rating: 4.5,
        downloads: '5000万+',
        url: 'https://www.bing.com/translator',
        themeColor: '#0078d4',
        desc: '微软在线翻译入口。'
    },
    {
        id: 'weread',
        name: '微信读书',
        category: 'lifestyle',
        icon: 'reading.png',
        developer: 'Tencent',
        rating: 4.7,
        downloads: '1亿+',
        url: 'https://weread.qq.com/',
        themeColor: '#1e80ff',
        desc: '微信读书网页版，适合在线阅读和书架管理。'
    },
    {
        id: 'douban-book',
        name: '豆瓣读书',
        category: 'lifestyle',
        icon: 'book.png',
        developer: 'Douban',
        rating: 4.5,
        downloads: '3000万+',
        url: 'https://book.douban.com/',
        themeColor: '#228a31',
        desc: '图书评分、书评和阅读发现平台。'
    },
    {
        id: 'poem',
        name: '古诗文网',
        category: 'lifestyle',
        icon: 'poem.png',
        developer: '古诗文网',
        rating: 4.6,
        downloads: '1000万+',
        url: 'https://www.gushiwenku.cn/',
        themeColor: '#8f4f24',
        desc: '古诗文检索、注释、译文和赏析入口。'
    },
    {
        id: 'health',
        name: '丁香医生',
        category: 'lifestyle',
        icon: 'health.png',
        developer: 'DXY',
        rating: 4.4,
        downloads: '3000万+',
        url: 'https://dxy.com/',
        themeColor: '#11a577',
        desc: '健康科普和医疗健康信息服务入口。'
    }
];
