param([switch]$Check)

$ErrorActionPreference = 'Stop'
$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$output = Join-Path $root 'js/core/storage-manifest.js'
$rootUri = [Uri]::new(($root.TrimEnd('\') + '\'))
$entries = [ordered]@{}
$targets = @((Join-Path $root 'index.html'), (Join-Path $root 'js'), (Join-Path $root 'css'), (Join-Path $root 'Theme'))
$files = foreach ($target in $targets) {
    if (Test-Path $target -PathType Leaf) { Get-Item $target }
    else { Get-ChildItem $target -File -Recurse }
}
foreach ($file in ($files | Sort-Object FullName)) {
    if ($file.FullName -eq $output) { continue }
    $path = [Uri]::UnescapeDataString($rootUri.MakeRelativeUri([Uri]::new($file.FullName)).ToString())
    $category = if ($path -eq 'index.html' -or $path.StartsWith('js/') -or $path.StartsWith('css/')) { 'core' } elseif ($path.StartsWith('Theme/Icon/App_icon/')) { 'app-icon' } else { 'resource' }
    $entries[$path] = [ordered]@{ size = [long]$file.Length; category = $category }
}
function Build([long]$selfSize) {
    $all = [ordered]@{}
    foreach ($pair in $entries.GetEnumerator()) { $all[$pair.Key] = $pair.Value }
    $all['js/core/storage-manifest.js'] = [ordered]@{ size = $selfSize; category = 'core' }
    $json = $all | ConvertTo-Json -Depth 4 -Compress
    "// Generated by scripts/generate-storage-manifest.ps1. Do not edit by hand.`r`nglobalThis.FluentOSStorageManifest = Object.freeze({ files: Object.freeze($json) });`r`n"
}
$size = 0L
for ($i = 0; $i -lt 10; $i++) {
    $content = Build $size
    $next = [Text.Encoding]::UTF8.GetByteCount($content)
    if ($next -eq $size) { break }
    $size = $next
}
$content = Build $size
if ($Check) {
    if (-not (Test-Path -LiteralPath $output -PathType Leaf)) {
        throw 'Storage manifest is missing. Run scripts/generate-storage-manifest.ps1.'
    }
    $actual = [IO.File]::ReadAllText($output)
    if ($actual -cne $content) {
        throw 'Storage manifest is stale. Run scripts/generate-storage-manifest.ps1.'
    }
    Write-Host "Storage manifest is current ($($entries.Count + 1) files)."
    return
}
[IO.File]::WriteAllText($output, $content, [Text.UTF8Encoding]::new($false))
Write-Host "Generated $output with $($entries.Count + 1) files."
