param(
    [string]$SystemVersion = '',
    [switch]$Check
)

$ErrorActionPreference = 'Stop'
$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$output = Join-Path $root 'js/core/resource-manifest.js'
$rootUri = [Uri]::new(($root.TrimEnd('\') + '\'))

if (-not $SystemVersion -and (Test-Path -LiteralPath $output -PathType Leaf)) {
    $existing = Get-Content -LiteralPath $output -Raw -Encoding UTF8
    $match = [regex]::Match($existing, "systemVersion:\s*'([^']+)'", 'CultureInvariant')
    if ($match.Success) { $SystemVersion = $match.Groups[1].Value }
}
if (-not $SystemVersion) {
    throw 'SystemVersion is required when no existing resource manifest is available.'
}
if ($SystemVersion -notmatch '^[0-9A-Za-z._-]+$') {
    throw 'SystemVersion may contain only letters, numbers, dots, underscores, and hyphens.'
}

$targets = @(
    (Join-Path $root 'index.html'),
    (Join-Path $root 'js'),
    (Join-Path $root 'css'),
    (Join-Path $root 'Theme')
)
$generatedFiles = @(
    (Join-Path $root 'js/core/resource-manifest.js'),
    (Join-Path $root 'js/core/storage-manifest.js')
)
$files = foreach ($target in $targets) {
    if (Test-Path -LiteralPath $target -PathType Leaf) {
        Get-Item -LiteralPath $target
    } else {
        Get-ChildItem -LiteralPath $target -File -Recurse
    }
}

$entries = [ordered]@{}
foreach ($file in ($files | Sort-Object FullName)) {
    if ($generatedFiles -contains $file.FullName) { continue }
    $path = [Uri]::UnescapeDataString($rootUri.MakeRelativeUri([Uri]::new($file.FullName)).ToString())
    $entries[$path] = (Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
}

$resourcesJson = $entries | ConvertTo-Json -Depth 3
$content = @"
// Generated by scripts/generate-resource-manifest.ps1. Do not edit by hand.
globalThis.FluentOSResourceManifest = Object.freeze({
    systemVersion: '$SystemVersion',
    resources: Object.freeze($resourcesJson)
});
"@ -replace '\r?\n', "`r`n"
$content += "`r`n"

if ($Check) {
    if (-not (Test-Path -LiteralPath $output -PathType Leaf)) {
        throw 'Resource manifest is missing. Run scripts/generate-resource-manifest.ps1.'
    }
    $actual = [IO.File]::ReadAllText($output)
    if ($actual -cne $content) {
        throw 'Resource manifest is stale. Run scripts/generate-resource-manifest.ps1.'
    }
    Write-Host "Resource manifest is current ($($entries.Count) revisions, Fluent OS $SystemVersion)."
    return
}

[IO.File]::WriteAllText($output, $content, [Text.UTF8Encoding]::new($false))
Write-Host "Generated $output with $($entries.Count) resource revisions for Fluent OS $SystemVersion."
