param(
    [string]$SystemVersion = '2.0.260702'
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$sourceFiles = @(
    (Join-Path $root 'index.html'),
    (Join-Path $root 'js/ui/boot.js'),
    (Join-Path $root 'js/ui/desktop.js')
)

$assetPattern = 'Theme/[A-Za-z0-9_./ -]+\.(?:png|jpe?g|svg|webp)'
$assets = foreach ($sourceFile in $sourceFiles) {
    $text = Get-Content -LiteralPath $sourceFile -Raw -Encoding UTF8
    [regex]::Matches($text, $assetPattern, 'IgnoreCase') | ForEach-Object Value
}
$assets += 'Theme/Profile_img/UserAva.png'
$assets += 1..10 | ForEach-Object { "Theme/Profile_img/$_.jpg" }
$assets += Get-ChildItem -LiteralPath (Join-Path $root 'Theme/Preload/OOBE') -Recurse -File | ForEach-Object {
    $_.FullName.Substring($root.Length + 1).Replace('\', '/')
}

$entries = [ordered]@{}
foreach ($asset in ($assets | Sort-Object -Unique)) {
    $relative = $asset.Replace('\', '/')
    $absolute = Join-Path $root ($relative.Replace('/', [IO.Path]::DirectorySeparatorChar))
    if (Test-Path -LiteralPath $absolute -PathType Leaf) {
        $entries[$relative] = (Get-FileHash -LiteralPath $absolute -Algorithm SHA256).Hash.ToLowerInvariant()
    }
}

$resourcesJson = $entries | ConvertTo-Json -Depth 3
$output = @"
// Generated by scripts/generate-resource-manifest.ps1. Do not edit by hand.
globalThis.FluentOSResourceManifest = Object.freeze({
    systemVersion: '$SystemVersion',
    resources: Object.freeze($resourcesJson)
});
"@

$target = Join-Path $root 'js/core/resource-manifest.js'
Set-Content -LiteralPath $target -Value $output -Encoding UTF8
Write-Host "Generated $target with $($entries.Count) resource revisions for Fluent OS $SystemVersion."
